
[package]
# Name of operating system package
name = "appackager"

description = "Keeper Technology application builder."
maintainer = "Keeper Technology LLC"


[dependencies]
# Values in this section must be lists of individual package
# specifications; version constraints must be included in the
# specification in Debian syntax.

requires = [
  "dpkg-dev",
  "cleanpython311",
  "lsb-release",
]


[installation]
directory = "/opt/appackager"
python = "/opt/cleanpython311/bin/python3"


[script.appackage]
entry-point = "appackage"
